[project]
name = "ontario-electricity-market"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=2,<3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "ruff>=0.14.10",
    "scipy>=1.16.3",
]
